// Code generated by go-mir. DO NOT EDIT.

package v1

import (
	"net/http"

	"github.com/alimy/mir/v2"

	mux "github.com/gorilla/mux"
)

// just use for mir.Any method to register
var httpMethods = mir.HttpMethods

type Registry interface {
	Register(http.ResponseWriter, *http.Request)
	Login(http.ResponseWriter, *http.Request)
	TokensInfo(http.ResponseWriter, *http.Request)
	GenerateTokens(http.ResponseWriter, *http.Request)
	RevokeTokens(http.ResponseWriter, *http.Request)
	TokenByName(http.ResponseWriter, *http.Request)
	Categories(http.ResponseWriter, *http.Request)
	SearchCrates(http.ResponseWriter, *http.Request)
	PublishCrates(http.ResponseWriter, *http.Request)
	SuggestCrates(http.ResponseWriter, *http.Request)
	CrateInfo(http.ResponseWriter, *http.Request)
	CrateOwnersInfo(http.ResponseWriter, *http.Request)
	PutCrateOwners(http.ResponseWriter, *http.Request)
	DelCrateOwners(http.ResponseWriter, *http.Request)
	YankCrate(http.ResponseWriter, *http.Request)
	UnyankCrate(http.ResponseWriter, *http.Request)
	DownloadCrate(http.ResponseWriter, *http.Request)

	mustEmbedUnimplementedRegistryServant()
}

// RegisterRegistryServant register Registry servant to mux
func RegisterRegistryServant(r *mux.Router, s Registry) {
	router := r.PathPrefix("/api/v1").Subrouter()

	// register routes info to router
	router.HandleFunc("account/register", s.Register).
		Methods("POST")
	router.HandleFunc("account/login", s.Login).
		Methods("POST")
	router.HandleFunc("account/tokens", s.TokensInfo).
		Methods("POST")
	router.HandleFunc("account/tokens", s.GenerateTokens).
		Methods("PUT")
	router.HandleFunc("account/tokens", s.RevokeTokens).
		Methods("DELETE")
	router.HandleFunc("account/tokens/{name}", s.TokenByName).
		Methods("GET")
	router.HandleFunc("categories", s.Categories).
		Methods("GET")
	router.HandleFunc("crates", s.SearchCrates).
		Methods("GET")
	router.HandleFunc("crates/new", s.PublishCrates).
		Methods("PUT")
	router.HandleFunc("crates/suggest", s.SuggestCrates).
		Methods("GET")
	router.HandleFunc("crates/{name}", s.CrateInfo).
		Methods("GET")
	router.HandleFunc("crates/{name}/owners", s.CrateOwnersInfo).
		Methods("GET")
	router.HandleFunc("crates/{name}/owners", s.PutCrateOwners).
		Methods("PUT")
	router.HandleFunc("crates/{name}/owners", s.DelCrateOwners).
		Methods("DELETE")
	router.HandleFunc("crates/{name}/{version}/yank", s.YankCrate).
		Methods("DELETE")
	router.HandleFunc("crates/{name}/{version}/unyank", s.UnyankCrate).
		Methods("PUT")
	router.HandleFunc("crates/{name}/{version}/download", s.DownloadCrate).
		Methods("GET")
}

// UnimplementedRegistryServant can be embedded to have forward compatible implementations.
type UnimplementedRegistryServant struct {
}

func (UnimplementedRegistryServant) Register(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method Register not implemented"))
}

func (UnimplementedRegistryServant) Login(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method Login not implemented"))
}

func (UnimplementedRegistryServant) TokensInfo(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method TokensInfo not implemented"))
}

func (UnimplementedRegistryServant) GenerateTokens(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method GenerateTokens not implemented"))
}

func (UnimplementedRegistryServant) RevokeTokens(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method RevokeTokens not implemented"))
}

func (UnimplementedRegistryServant) TokenByName(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method TokenByName not implemented"))
}

func (UnimplementedRegistryServant) Categories(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method Categories not implemented"))
}

func (UnimplementedRegistryServant) SearchCrates(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method SearchCrates not implemented"))
}

func (UnimplementedRegistryServant) PublishCrates(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method PublishCrates not implemented"))
}

func (UnimplementedRegistryServant) SuggestCrates(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method SuggestCrates not implemented"))
}

func (UnimplementedRegistryServant) CrateInfo(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method CrateInfo not implemented"))
}

func (UnimplementedRegistryServant) CrateOwnersInfo(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method CrateOwnersInfo not implemented"))
}

func (UnimplementedRegistryServant) PutCrateOwners(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method PutCrateOwners not implemented"))
}

func (UnimplementedRegistryServant) DelCrateOwners(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method DelCrateOwners not implemented"))
}

func (UnimplementedRegistryServant) YankCrate(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method YankCrate not implemented"))
}

func (UnimplementedRegistryServant) UnyankCrate(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method UnyankCrate not implemented"))
}

func (UnimplementedRegistryServant) DownloadCrate(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusNotImplemented)
	rw.Write([]byte("method DownloadCrate not implemented"))
}

func (UnimplementedRegistryServant) mustEmbedUnimplementedRegistryServant() {}
